Carol V2
ORANGO-IO/carol pull request #2
Opened 2024-12-06 21:30 UTC by Henrique-Gomesz

2024-12-24 22:23 UTC, filiperochalopes requested changes

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/main-form.jsx
> +                />
Não encontrei aqui o campo de idade, conforme nosso documento de requisitos deve ser um campo separado e capaz de preencher, em alguns casos o nosso usuario pode apenas preencher a idade direto sem a data de nascimento, pode ser mais facil.

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/birthday-validation.js
> +import { DATE_REGEX } from "../../../regex";
relative import

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/diastolic-pressure-validation.js
> +    return value >= 42 && value <= 63; // 1 infancia
essas faixas etarias se repetem entre arquivos, seria importante se fosse criada alguma regra para nao ter que repetir esse intervalo em todos os arquivos por exemplo uma funcao validateVitalsByAge

```js
validateVitalsByAge({
neonate: ...
infant:
toddler
preschooler:
schoolage
adolescent
```

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/heart-rate-validation.js
> +import { calculateAge } from "../../../utils/calculate-age-from-date";
relative imports

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/heart-rate-validation.js
> +}
esse bloco de codigo se repete, importante criar uma solucao generica como ja comentado previamente

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/respiratory-rate-validation.js
> +  if (age == undefined || age == "") {
trecho de codigo repetido

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/main-form/validation/systolic-pressure-validation.js
> +  if (age == undefined || age == "") {
trecho repetido

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/components/results/results.jsx
> +import { calculateAge } from "../../utils/calculate-age-from-date";
relative imports, nao repetirei mais esse comentario, favor corrigir todos os imports relativos

2024-12-24 22:23 UTC, filiperochalopes commented on frontend/src/index.css
> +:root {
Nao entendi esse arquivo, é algum tipo de base css? se for, deve ser utilizado de acordo com o styled components: [GlobalStyle](https://styled-components.com/docs/api#createglobalstyle)

2025-01-10 03:47 UTC, Henrique-Gomesz commented on frontend/src/components/form-toggle/components/switch-label/switch-label.styles.jsx
> +export const RightImage = styled.img``;
Para deixar o componente principal mais legível criamos uma varíavel nomeada que deixa mais semantico

2025-01-10 03:47 UTC, Henrique-Gomesz commented on frontend/src/components/logo/logo.styles.jsx
> +export const LogoComponent = styled.img``;
Para deixar o componente principal mais legível criamos uma varíavel nomeada que deixa mais semantico

2025-01-10 03:48 UTC, Henrique-Gomesz commented on frontend/src/components/main-form/main-form.jsx
> +                />
O campo de idade esta no mesmo componente BirthdayField, é possível digitar a idade através da data de nascimento ou através do input direto.

2025-01-10 04:00 UTC, Henrique-Gomesz commented on README.md
> +consultável o Protocolo do Hospital de Brasília. Mais informações e Live:
Foi o formatador, foi ajustado.

2025-01-10 04:00 UTC, Henrique-Gomesz commented on README.md
> +   host:container, so if you want your database exposed on 3307, ports will be
Foi ajustado.

2025-01-14 01:18 UTC, Henrique-Gomesz commented on frontend/src/components/form-errors/form-errors.jsx
> +import { Container, Error } from "./form-errors.styles";
ok

2025-02-01 14:22 UTC, filiperochalopes approved these changes

2025-02-01 14:22 UTC, filiperochalopes commented on frontend/.eslintrc.json
> +    "prettier/prettier": "error"
Vamos trabalhar com prettier como warning e não como erro

2025-03-24 14:08 UTC, merged